name: Print Node Info

on:
  push:
    branches: [master]

jobs:
  node-info:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3

      - name: Print Node.js version
        run: node -v || echo "Node is not installed yet" 

      - name: List Project Files
        run: ls -la 
